### ISSUE TITLE
Undefined behaviour in FindMemoryPreferences

### ISSUE THREAD

**Issue by markridgewell** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#368]
UBSan reports undefined behaviour on the line:
```cpp
const bool deviceAccess = (bufImgUsage & ~(VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT)) != 0;
```

The problem is that the `VK_BUFFER_USAGE_TRANSFER_*_BIT` constants are members of an unscoped enum, so they are signed, at least in Clang. This means the complement is negative but is implictly cast to an uint32_t before the bitwise and.

Casting the flags before taking the complement seems to fix the issue, e.g:
```cpp
const bool deviceAccess = (bufImgUsage & ~static_cast<VkFlags>(VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_TRANSFER_SRC_BIT)) != 0;
```

Here's the report from ubsan:
```
2023-09-10T22:11:04.6623809Z 1: /home/runner/work/Teide/Teide/build/ninja/vcpkg_installed/x64-linux-ubsan/include/vk_mem_alloc.h:3684:50: runtime error: implicit conversion from type 'int' of value -4 (32-bit, signed) to type 'VkFlags' (aka 'unsigned int') changed the value to 4294967292 (32-bit, unsigned)
2023-09-10T22:11:04.8284642Z 1:     #0 0x56291dcfdd0a in FindMemoryPreferences(bool, VmaAllocationCreateInfo const&, unsigned int, unsigned int&, unsigned int&, unsigned int&) /home/runner/work/Teide/Teide/build/ninja/vcpkg_installed/x64-linux-ubsan/include/vk_mem_alloc.h:3684:50
2023-09-10T22:11:04.8299901Z 1:     #1 0x56291dcfd526 in VmaAllocator_T::FindMemoryTypeIndex(unsigned int, VmaAllocationCreateInfo const*, unsigned int, unsigned int*) const /home/runner/work/Teide/Teide/build/ninja/vcpkg_installed/x64-linux-ubsan/include/vk_mem_alloc.h:14885:9
2023-09-10T22:11:04.8302281Z 1:     #2 0x56291dcfff66 in VmaAllocator_T::AllocateMemory(VkMemoryRequirements const&, bool, bool, VkBuffer_T*, VkImage_T*, unsigned int, VmaAllocationCreateInfo const&, VmaSuballocationType, unsigned long, VmaAllocation_T**) /home/runner/work/Teide/Teide/build/ninja/vcpkg_installed/x64-linux-ubsan/include/vk_mem_alloc.h:15073:15
2023-09-10T22:11:04.8305920Z 1:     #3 0x56291dd155ad in vmaCreateImage /home/runner/work/Teide/Teide/build/ninja/vcpkg_installed/x64-linux-ubsan/include/vk_mem_alloc.h:17342:26
```

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this issue. I fixed it as you proposed.
